apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer  # This makes the service reachable over the internet
  clusterIP: None  # Headless service (important for StatefulSet)
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

